/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-10-07 04:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- ##### Instagram Area Start ##### -->\r\n");
      out.write("    <div class=\"instagram-feed-area d-flex flex-wrap\">\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta01.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta01.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta02.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta02.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta03.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta03.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta04.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta04.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta05.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta05.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta06.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta06.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta07.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta07.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta08.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta08.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta09.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta09.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Single Instagram -->\r\n");
      out.write("        <div class=\"single-instagram\">\r\n");
      out.write("            <img src=\"resources/img/bg-img/insta010.jpg\" alt=\"\">\r\n");
      out.write("            <!-- Image Zoom -->\r\n");
      out.write("            <!-- <a href=\"resources/img/bg-img/insta010.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ##### Instagram Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("    <footer class=\"footer-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 col-sm-5\">\r\n");
      out.write("                    <!-- Copywrite Text -->\r\n");
      out.write("                    <!-- <p class=\"copywrite-text\"><a href=\"#\">Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.</p> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-sm-7\">\r\n");
      out.write("                    <!-- Footer Nav -->\r\n");
      out.write("                    <div class=\"footer-nav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"active\"><a href=\"/\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"about\">About Us</a></li>\r\n");
      out.write("                            <li><a href=\"notice\">Notice</a></li>\r\n");
      out.write("                            <li><a href=\"board\">Board</a></li>\r\n");
      out.write("                            <li><a href=\"map\">CafeMap</a></li>\r\n");
      out.write("                            <li><a href=\"voclist\">VOC</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
