/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-10-12 14:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1569743003710L));
    _jspx_dependants.put("jar:file:/F:/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/CoffeeBeans/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("<!-- Title -->\r\n");
      out.write("<title>커피콩스(CoffeeBeans)</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"resources/img/core-img/abc.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/ddd.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".a {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b {\r\n");
      out.write("\tcolor: brown;\r\n");
      out.write("}\r\n");
      out.write(".c {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Preloader -->\r\n");
      out.write("\t<div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t<div class=\"preloader-content\">\r\n");
      out.write("\t\t\t<h3>Cooking in progress..</h3>\r\n");
      out.write("\t\t\t<div id=\"cooking\">\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"area\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sides\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pan\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"handle\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pancake\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pastry\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Header Area Start ##### -->\r\n");
      out.write("\t<header class=\"header-area\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Top Header Area -->\r\n");
      out.write("\t\t<div class=\"top-header-area bg-img bg-overlay\"\r\n");
      out.write("\t\t\tstyle=\"background-image: url(resources/img/bg-img/header1.jpg);\">\r\n");
      out.write("\t\t\t<div class=\"container h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"row h-100 align-items-center justify-content-between\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Top Social Info -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-social-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.pinterest.co.kr/\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Pinterest\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://www.facebook.com/\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Facebook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\" aria-hidden=\"true\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://twitter.com/?lang=ko\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\" aria-hidden=\"true\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://dribbble.com/\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Dribbble\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://www.behance.net/\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Behance\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-behance\" aria-hidden=\"true\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://kr.linkedin.com/\" data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-placement=\"bottom\" title=\"Linkedin\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-linkedin\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-6 col-lg-5 col-xl-4\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Top Search Area -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-search-area\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"search\" name=\"top-search\" id=\"topSearch\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Logo Area -->\r\n");
      out.write("\t\t<div class=\"logo-area\">\r\n");
      out.write("\t\t\t<a href=\"/\"><img class=\"logo\"\r\n");
      out.write("\t\t\t\tsrc=\"resources/img/core-img/newlogo.png\" alt=\"\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navbar Area -->\r\n");
      out.write("\t\t<div class=\"bueno-main-menu\" id=\"sticker\">\r\n");
      out.write("\t\t\t<div class=\"classy-nav-container breakpoint-off\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<!-- Menu -->\r\n");
      out.write("\t\t\t\t\t<nav class=\"classy-navbar justify-content-between\" id=\"buenoNav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Toggler -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"toggler\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/img/core-img/toggler.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Navbar Toggler -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"classy-navbar-toggler\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Menu -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"classy-menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Close Button -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"classycloseIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cross-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"top\"></span><span class=\"bottom\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav Start -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"classynav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"about\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"notice\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"board\">Board</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"map\">CafeMap</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"voclist\">VOC</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <li><a href=\"#\">Pages</a>\r\n");
      out.write("                                        <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                            <li><a href=\"catagory.html\">Catagory</a></li>\r\n");
      out.write("                                            <li><a href=\"catagory-post.html\">Catagory Post</a></li>\r\n");
      out.write("                                            <li><a href=\"single-post.html\">Single Post</a></li>\r\n");
      out.write("                                            <li><a href=\"receipe.html\">Recipe</a></li>\r\n");
      out.write("                                            <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"#\">Recipes</a>\r\n");
      out.write("                                        <div class=\"megamenu\">\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"#\">- Recipe</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Bread</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Breakfast</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Meat</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Fastfood</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Salad</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Soup</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"#\">- Recipe</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Bread</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Breakfast</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Meat</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Fastfood</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Salad</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Soup</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"#\">- Recipe</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Bread</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Breakfast</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Meat</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Fastfood</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Salad</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Soup</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            <ul class=\"single-mega cn-col-4\">\r\n");
      out.write("                                                <li><a href=\"#\">- Recipe</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Bread</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Breakfast</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Meat</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Fastfood</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Salad</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">- Soup</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- ##### Header Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Treading Post Area Start ##### -->\r\n");
      out.write("\t<div class=\"treading-post-area\" id=\"treadingPost\">\r\n");
      out.write("\t\t<div class=\"close-icon\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<h4>'커피(Coffee)' 관련 추천사이트</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"http://www.micoffee.co.kr/\" target=\"_blank\"><img id=\"firstimg\" src=\"resources/img/bg-img/9.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">원두 판매 사이트</a> \r\n");
      out.write("\t\t\t\t<a href=\"http://www.micoffee.co.kr/\" class=\"post-title\" target=\"_blank\">M I Coffee(엠 아이 커피)</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">동남아시아 / 남아메리카 등등 <br/> 해당 지역에서 생산된 수입원두의 <br/> 구입이 가능한 사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"http://coffee2u.co.kr/\" target=\"_blank\"><img id=\"firstimg2\" src=\"resources/img/bg-img/10.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">원두 커피 쇼핑몰</a> \r\n");
      out.write("\t\t\t\t<a href=\"http://coffee2u.co.kr/\"class=\"post-title\" target=\"_blank\">Coffee2U(커피투유)</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">드립백커피 / 더치커피 / <br/> 스페셜티커피 / 싱글오리진 / <br/> 블랜드커피 뿐만아니라 <br/> 커피선물세트 or 커피용품의 <br/> 구매가 가능한 사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"http://www.retreebean.co.kr/shop/main/index.php\" target=\"_blank\"><img id=\"firstimg3\" src=\"resources/img/bg-img/11.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">원두 / 차 및 커피머신 판매사이트</a> \r\n");
      out.write("\t\t\t\t<a href=\"http://www.retreebean.co.kr/shop/main/index.php\" class=\"post-title\" target=\"_blank\">ReTreeBean(리트리빈)</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">아시아 / 중남미 / 아시아,태평양 / <br/> 세계3대 커피 / 블랜딩 생두 뿐만 아니라, 허브차와 같은 차도 판매하며, 커피머신도 구매가능한 사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"https://penielcompany.modoo.at/\" target=\"_blank\"><img id=\"firstimg4\" src=\"resources/img/bg-img/12.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">바리스타 교육기관</a> \r\n");
      out.write("\t\t\t\t<a href=\"https://penielcompany.modoo.at/\" class=\"post-title\" target=\"_blank\">브니엘 커피 로스터스</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">로스팅 마스터 / 커피 커핑 마스터 / 핸드드립 마스터 / 에스프레소 마스터 / 라떼아스 마스터 등 <br/> 바리스타 교육 사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"https://brownbagcoffee.co.kr/\" target=\"_blank\"><img id=\"firstimg5\" src=\"resources/img/bg-img/13.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">홈카페 원두추천 사이트</a> \r\n");
      out.write("\t\t\t\t<a href=\"https://brownbagcoffee.co.kr/\" class=\"post-title\" target=\"_blank\">BrownBag Coffee(브라운백 커피)</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">커피 시음을 통해 나만의 홈카페를 <br/> 구성하는데 도움을 추는 <br/> 원두추천 및 구매사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Single Blog Post -->\r\n");
      out.write("\t\t<div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\r\n");
      out.write("\t\t\t<!-- Blog Thumbnail -->\r\n");
      out.write("\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t<a href=\"http://ssadagucoffee.co.kr/\" target=\"_blank\"><img id=\"firstimg6\" src=\"resources/img/bg-img/14.PNG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Blog Content -->\r\n");
      out.write("\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"post-tag\">가성비의 저렴한 커피 추천사이트</a> \r\n");
      out.write("\t\t\t\t<a href=\"http://ssadagucoffee.co.kr/\" class=\"post-title\" target=\"_blank\">SDG커피(싸다구커피)</a>\r\n");
      out.write("\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-date\">October 03, 2019</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"post-author\">200G ~ 1KG 까지 다양한 용량의 <br/> 커피를 가성비 좋게 저렴하게 <br/> 이용할 수 있게 해주는 사이트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ##### Treading Post Area End ##### -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"resources/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('ul#loginbar').css({\r\n");
      out.write("\t\t\t'margin-left':'0%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg2').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg3').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg4').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg5').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('img#firstimg6').css({\r\n");
      out.write("\t\t\t'width':'100%',\r\n");
      out.write("\t\t\t'height':'100%'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/includes/header.jsp(205,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SessionEMAIL==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- Login/Register -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"login-area\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"/login\">Login / </a> <a href=\"/signup\">Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/includes/header.jsp(211,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SessionEMAIL=='gkwlstn2001@naver.com'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"login-area\"> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul id=\"loginbar\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h6>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><h6 class=\"b\">[관리자]</h6></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SessionEMAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"adminpage\">관리자 페이지</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"/signupdelete\">회원탈퇴</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t/\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"/logout\">Logout</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- <ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"#\">Member</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Update</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Delete</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"login-area\"> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<ul id=\"loginbar\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><h6 class=\"b\">[로그인]</h6></li> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SessionEMAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"/signupupdate\">회원정보 수정</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"/signupdelete\">회원탈퇴</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t/\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"/logout\">Logout</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<!-- <ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"a\"><a href=\"#\">Member</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Update</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Delete</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
