/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-10-20 13:04:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CoffeeBeans/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1569743003710L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>회원가입(SignUp)</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"resources/width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" href=\"resources/images2/icons/favicon.ico\"/>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/fonts/font-awesome-4.7.0.2/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/fonts/Linearicons-Free-v1.0.0.2/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/fonts/iconic2/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/vendor2/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/util2.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/main2.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"resources/img/core-img/abc.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t.a {\r\n");
      out.write("\t\tdisplay : inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<body style=\"background-color: #ffffff;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"limiter\">\r\n");
      out.write("\t\t<div class=\"container-login100\">\r\n");
      out.write("\t\t\t<div class=\"login100-more\" style=\"background-image: url('resources/images2/bg-010.jpg');\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50\">\r\n");
      out.write("\t\t\t\t<form class=\"login100-form validate-form\" action=\"/signupok\" method=\"post\"  id=\"idcheck\">\r\n");
      out.write("\t\t\t\t\t<span class=\"login100-form-title p-b-59\">\r\n");
      out.write("\t\t\t\t\t\tSign Up\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate = \"Valid email is required: ex@abc.xyz\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"a\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label-input100\">Email</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"a\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrap-login100-form-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login100-form-bgbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"login100-form-btn\" onclick=\"idcheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t중복확인 체크\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input100\" id=\"writeemail\" type=\"email\" name=\"EMAIL\" id=\"EMAIL\" value=\"\" placeholder=\"Email addess...\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate = \"Password is required\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label-input100\">Password</span>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input100\" type=\"password\" name=\"PASSWORD\" id=\"PASSWORD\" value=\"\" placeholder=\"*************\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate=\"Name is required\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label-input100\">Full Name</span>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input100\" type=\"text\" name=\"FULLNAME\" id=\"FULLNAME\" value=\"\" placeholder=\"Name...\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate=\"Address is required\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label-input100\">Address</span>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input100\" type=\"text\" name=\"ADDRESS\" id=\"ADDRESS\" value=\"\" placeholder=\"주소창을 클릭하시면 창이 뜹니다\" onclick=\"addresspopup()\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate=\"PhoneNumber is required\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"label-input100\">PhoneNumber</span>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input100\" type=\"number\" name=\"PHONENUMBER\" id=\"PHONENUMBER\" value=\"\" placeholder=\"PhoneNumber...\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"flex-m w-full p-b-33\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"contact100-form-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input-checkbox100\" id=\"ckb1\" type=\"checkbox\" name=\"remember-me\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"label-checkbox100\" for=\"ckb1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tI agree to the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"txt2 hov1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTerms of User\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container-login100-form-btn\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrap-login100-form-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login100-form-bgbtn\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"login100-form-btn\" onclick=\"return buttonchecking()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t회원가입\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/\" class=\"dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30\">\r\n");
      out.write("\t\t\t\t\t\t\tHome\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-long-arrow-right m-l-5\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar buttoncheck = \"false\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction idcheck() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax ({\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\turl : \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("\t\t\t\tdata : $('form#idcheck').serialize(),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif(data==\"fail\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"중복된 아이디가 있습니다. 다시입력하세요!\");\r\n");
      out.write("\t\t\t\t\t\t$('input#writeemail').val(\"\");\r\n");
      out.write("\t\t\t\t\t} else if(data==\"success\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"중복된 아이디가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\tbuttoncheck = \"true\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(request,status,error){\r\n");
      out.write("\t            \t// alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t       \t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction buttonchecking() {\r\n");
      out.write("\t\t\tif(buttoncheck == \"false\") {\r\n");
      out.write("\t\t\t\talert(\"아이디 중복체크는 필수항목입니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else if(buttoncheck == \"true\" && $('input#EMAIL').val() !=\"\" && $('input#PASSWORD').val() !=\"\" \r\n");
      out.write("\t\t\t\t\t&& $('input#FULLNAME').val() !=\"\" && $('input#ADDRESS').val() !=\"\" && $('input#PHONENUMBER').val() !=\"\") {\r\n");
      out.write("\t\t\t\talert(\"회원가입 성공! 환영합니다 ^^\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction addresspopup() {\r\n");
      out.write("\t\t\tif($('input#ADDRESS').val()!=\"\") {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"ADDRESS\").focus();\r\n");
      out.write("\t\t\t\talert(\"새로 입력하시려면 주소를 모두 지우신뒤에 주소창을 클릭해주세요\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t    new daum.Postcode({\r\n");
      out.write("\t\t\t        oncomplete: function(data) {\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t        \t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t                var addr = ''; // 주소 변수\r\n");
      out.write("\t\t                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("\t\t                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("\t\t                    addr = data.roadAddress;\r\n");
      out.write("\t\t                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("\t\t                    addr = data.jibunAddress;\r\n");
      out.write("\t\t                }\r\n");
      out.write("\r\n");
      out.write("\t\t                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("\t\t                if(data.userSelectedType === 'R'){\r\n");
      out.write("\t\t                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("\t\t                        extraAddr += data.bname;\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("\t\t                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t                    if(extraAddr !== ''){\r\n");
      out.write("\t\t                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("\t\t                    document.getElementById(\"ADDRESS\").value = extraAddr;\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                } else {\r\n");
      out.write("\t\t                    document.getElementById(\"ADDRESS\").value = '';\r\n");
      out.write("\t\t                }\r\n");
      out.write("\r\n");
      out.write("\t\t                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t                document.getElementById('ADDRESS').value += data.zonecode;\r\n");
      out.write("\t\t                document.getElementById(\"ADDRESS\").value += addr;\r\n");
      out.write("\t\t                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("\t\t                document.getElementById(\"ADDRESS\").focus();\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }).open();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/bootstrap/js/popper.js\"></script>\r\n");
      out.write("\t<script src=\"resources/vendor2/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/select2/select2.min.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/vendor2/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/vendor2/countdowntime/countdowntime.js\"></script>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"resources/js/main2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/signup.jsp(145,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("idcheck");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
